#!/usr/bin/expect

# usage : ./$0 [host] [username] [password] [password_for_pubkey]

set timeout 20

set hst [lindex $argv 0] 
set usr [lindex $argv 1]
set pas [lindex $argv 2]
set pub [lindex $argv 3]

eval spawn ssh $usr@$hst
expect {
    ".ssh/id_rsa':" {
        send "$pub\r";
    }
    "(yes/no)" {
        send "yes\r";
        expect "assword:" {
            send "$pas\r";
        }
    }
    "assword:" {
        send "$pas\r";
    }
}
interact
